grammar json
  value   <- string / number / object / array / special
  array   <- "[" _ ( value ( _ "," _ value)* )? _ "]" <ArrayNode>
  object  <- "{" _ ( (string _ ":" _ value) ( _ "," _ string _ ":" _  value)* )? _ "}" <ObjectNode>
  string  <- "\"" ( [^"\\] / ("\\" ["bfnrt\\/]) / hex )* "\"" <StringNode>
  number  <- "-"? ( ("0" / [1-9] [0-9]*) ("." [0-9]+)? ( ("e" / "E") ("+" / "-")? [0-9]+ )? ) <NumberNode>
  special <- "true" / "false" / "null <SpecialNode>"
  hex     <- "\\u" [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F]
  _       <- [ \n\t]*